# Generated by Django 5.2 on 2026-01-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payment_link_payment_payment_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='link_payment',
            field=models.URLField(blank=True, max_length=800, null=True, verbose_name='Ссылка на оплату'),
        ),
    ]
